# Welcome to Jekyll!
#

# Site settings
title: Patrick Best
description: |
  Software Engineer
owner: Patrick Best
first_published: 2016 
email: patrickbest1991@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dynamicpat.github.io/" # the base hostname & protocol for your site
social:
  github: https://github.com/DynamicPat
  linkedin-square: https://linkedin.com/in/patrick-best
  #facebook-official: https://facebook.com/<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  twitter: https://twitter.com/PatrickB2Me
  soundcloud: https://soundcloud.com/patrickbest
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
